# Generated by Django 2.0.2 on 2020-11-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semi_name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=100)),
                ('area_of_seminar', models.TextField(max_length=150)),
                ('semi_schedule', models.TextField(blank=True)),
                ('seni_men_num', models.IntegerField()),
                ('seni_women_num', models.IntegerField()),
                ('juni_men_num', models.IntegerField()),
                ('juni_women_num', models.IntegerField()),
                ('feature', models.TextField(blank=True)),
                ('interaction', models.IntegerField(choices=[(1, '少ない'), (2, '比較的少ない'), (3, '普通'), (4, '比較的多い'), (5, '多い'), (6, '選択してください')], default=6)),
                ('busyness', models.IntegerField(choices=[(1, '忙しくない'), (2, '比較的忙しくない'), (3, '普通'), (4, '比較的忙しい'), (5, '忙しい'), (6, '選択してください')], default=6)),
                ('semi_update_at', models.DateTimeField(auto_now=True)),
                ('semi_image1', models.ImageField(blank=True, null=True, upload_to='seminar_photos')),
                ('semi_image2', models.ImageField(blank=True, null=True, upload_to='seminar_photos')),
                ('semi_image3', models.ImageField(blank=True, null=True, upload_to='seminar_photos')),
                ('semi_image4', models.ImageField(blank=True, null=True, upload_to='seminar_photos')),
                ('semi_image5', models.ImageField(blank=True, null=True, upload_to='seminar_photos')),
                ('semi_image6', models.ImageField(blank=True, null=True, upload_to='seminar_photos')),
            ],
        ),
    ]
