# Generated by Django 2.0.2 on 2020-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0002_seminar_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='message_for_sutudent',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seminar',
            name='on_offline',
            field=models.IntegerField(choices=[(1, 'オンライン'), (2, '対面'), (3, '未定')], default=3),
        ),
        migrations.AddField(
            model_name='seminar',
            name='visitable_date',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
