# Generated by Django 2.0.2 on 2020-11-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0003_auto_20201111_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_num', models.CharField(max_length=7)),
                ('booking_date', models.TextField(max_length=50)),
            ],
        ),
    ]
