# Generated by Django 2.0.2 on 2020-11-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0005_booking_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='busyness',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='interaction',
        ),
    ]
