# Generated by Django 2.0.2 on 2020-11-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0010_auto_20201122_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='department',
            field=models.IntegerField(choices=[(1, '未選択'), (2, '法律学科'), (3, '地域行政学科')], default=1),
        ),
        migrations.AddField(
            model_name='seminar',
            name='teach_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
