# Generated by Django 2.0.2 on 2020-11-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0012_auto_20201128_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='message_for_sutudent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='visitable_date',
            field=models.TextField(blank=True),
        ),
    ]
